version: '3.8'

services:
  db:
    image: postgres:16.2
    container_name: uniboost-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
    container_name: uniboost-api
    depends_on:
      - db
    ports:
      - '9080:9080'
    environment:
      # DB connection for Spring
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

volumes:
  postgres_data:
